services:
  orbitx:
    image: ${DOCKER_REGISTRY-}orbitx
    build:
      context: .
      dockerfile: OrbitX/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: orbitx-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: